---
title: '分位数を用いた分布の比較'
subtitle: 'Q-Qプロット導入説明'
author: '東京国際大学 データサイエンス教育研究所 竹田 恒'
date: '2022-09-22'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)
```

------------------------------------------------------------------------

```{r echo=FALSE}
# カラーパレット（透過色）
RGBS <- c(rgb(1, 0, 1, .25), # ピンク
          rgb(0, 0, 1, .25), # ラベンダー
          rgb(0, 1, 0, .25)) # グリーン
GRAY <- rgb(.5, .5, .5, .25) # グレー
```

## データ

次の2つの標本X1，X2を比較に用いる。 \
X2はX1の約10倍の尺度を持つ。

```{r}
x1 <- c(1, 2, 3, 4, 5, 5, 6, 7, 8) 
x2 <- c(10, 20, 25, 40, 50, 50, 65, 70, 80) 
```

```{r}
hist(x1)
hist(x2)
```

------------------------------------------------------------------------

## 四分位数

```{r}
(q1 <- quantile(x1, probs = c(1/4, 2/4, 3/4)))
(q2 <- quantile(x2, probs = c(1/4, 2/4, 3/4)))
```

## 四分位数同士の比較（散布図）

標本の尺度が異なっていても，
分布形状が同じであれば一直線上にプロットされる。

```{r echo=FALSE}
matplot(x = q1, y = q2, pch = 16,
        main = '散布図（四分位数同士の比較）',
        xlab = '標本1分位数',
        ylab = '標本2分位数')
grid()
abline(a = 0, b = 10, col = 'red')
```