---
title: 'ヒストグラム'
author: '東京国際大学 データサイエンス教育研究所 竹田 恒'
date: '2022-08-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)
```

---

## データ
```{r}
set.seed(2)
d <- data.frame(
  u = rnorm(n = 100, mean =  0, sd = 1),
  v = rnorm(n = 100, mean =  2, sd = 2),
  w = rnorm(n = 100, mean = -2, sd = 3)) 

str(d)
```

##### 要約統計量
```{r}
summary(d)
```

```{r echo=TRUE}
# カラーパレット
# (https://www.rapidtables.com/web/color/RGB_Color.html)
COL <- c(rgb(255,   0, 255,  55, max = 255), # ピンク
         rgb(  0,   0, 255,  55, max = 255), # ラベンダー
         rgb(  0, 255,   0,  55, max = 255)) # ライトグリーン
```

---

## ヒストグラム
```{r}
# 階級
BINS <- seq(-20, 20, 1)

# 枠
hist(d$u, col = 0, border = 0,
     breaks = BINS, # default:"Sturges","Scott","FD"
     right = F,     # [a, b), default T:(a, b]
     main = '主タイトル',
     xlab = 'x軸ラベル［単位］',
     ylab = '度数')

# 罫線
grid()

# プロット
hist(d$u, breaks = BINS, col = COL[1], add = T)
hist(d$v, breaks = BINS, col = COL[2], add = T)
hist(d$w, breaks = BINS, col = COL[3], add = T)

# 凡例
legend('topleft', fill = COL, legend = c('U', 'V', 'W'))

```
