---
title: '時系列グラフ'
subtitle: '演習課題'
author: '東京国際大学 データサイエンス教育研究所 竹田 恒'
date: '2022-08-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)
```

---

## データ
```{r}
d1 <- read.csv("電力使用量_2021-05-01.csv")
d2 <- read.csv("電力使用量_2022-05-01.csv")
head(d1)
head(d2)

d <- data.frame(y1 = d1$mankw, 
                y2 = d2$mankw)

# 時刻 (format > ?strptime）
Sys.setlocale("LC_TIME", "ja_JP.UTF-8")
rownames(d) <- ct <- as.POSIXct(paste(d1$date, d1$time), 
                                format = "%Y/%m/%d %H:%M", tz = "Japan")

nr <- nrow(d)
nc <- ncol(d)

head(d)
library(knitr)
kable(d)
```

#### 要約統計量
```{r}
summary(d)
```

```{r echo=TRUE}
# カラーパレット
# (https://www.rapidtables.com/web/color/RGB_Color.html)
COL <- c(rgb(255,   0,   0,  255, max = 255), # 赤
         rgb(  0,   0, 255,  255, max = 255), # 青
         rgb(  0, 155,   0,  255, max = 255)) # 緑
```

---

## 時系列グラフ
```{r}
# 枠 
matplot(d, 
        type = "n", xaxt = "n", # プロット，x軸を表示しない．
        ylim = c(2000, 3000),
        main = '2021-05-01と2022-05-01の毎時電力使用量',
        xlab = '５月１日',
        ylab = '電力使用量［万kW］')

# x軸
at.x <- seq(1, nr, 2)
axis(1, at = at.x, labels = format(ct, "%H:%M")[at.x])

# 罫線
abline(lty = 2, col = gray(.5, .25),
       h = seq(0, 3000, 200),
       v = at.x)

# プロット
matlines(d$y1, type = "o", pch = 1, lty = 1, col = COL[1])
matlines(d$y2, type = "o", pch = 2, lty = 2, col = COL[2])


# 凡例
legend('topleft', col = COL, pch = 1:nc, lty = 1:nc,
       legend = c('Y2021', 'Y2022'))
```